spring:
  profiles:
    active: prod
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: true
      FAIL_ON_UNKNOWN_PROPERTIES: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
server:
  port: ${APP_PORT:8081}
  jwt:
    token-info-uri: ${AUTH_APP_URL:http://localhost:9002}/oauth/check_token
    auth-url: ${AUTH_APP_URL:http://localhost:9002}/oauth/authorize
    token-url: ${AUTH_APP_URL:http://localhost:9002}/oauth/token
    client-id: postman
    client-secret: ${OAUTH_CLIENT_SECRET}
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.test: ERROR
springdoc:
  swagger-ui:
    oauth:
      client-id: postman
      client-secret: ${OAUTH_CLIENT_SECRET}
      auth-url: http://localhost:${AUTH_APP_PORT:9002}/oauth/authorize
      token-url: http://localhost:${AUTH_APP_PORT:9002}/oauth/token
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gift_app
    username: postgres
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 80
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=0
    username: sa
    password: password
    driver-class-name: org.h2.Driver
